name: Build Docker Images on Tag

on:
  push:
    tags:
      - '*'

jobs:
  master:
    name: Build and Push Master Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
           context: .
           file: Dockerfile
           push: true
           tags: |
            ghcr.io/c-l-a-x-o-n/web/prod:${{ github.ref_name }}
            ghcr.io/c-l-a-x-o-n/web/prod:latest
